# Generated by Django 4.2.7 on 2023-12-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
